### ISSUE TITLE
会导致其某些需要挂载的应用无法挂载

### ISSUE THREAD

**Issue by fxynb399** [sidex15/ksu_module_susfs#86]
如题，我把sufs中所有关于挂载的选项都取消了勾选，但是也不生效。我的应用linux deploy运行后会报错：/ ... mount: mounting /data/linux on /data/local/mnt failed: No such file or directory，
但是如果我把sufs彻底移除那就正常了。

![Image](https://github.com/user-attachments/assets/7aba7cbe-1023-4aa0-b71c-3aaee5618223)

![Image](https://github.com/user-attachments/assets/f71458db-2f4d-4514-9d90-569953df08f7)

![Image](https://github.com/user-attachments/assets/25dcb142-7c1a-4dff-ac9b-07acd7454ba3)

这是配置详情：

![Image](https://github.com/user-attachments/assets/b4cda9b3-30e6-4a4c-8e5c-f3986af2dada)

**Comment by sidex15** [comment]
Try to downgrade to R16 if that works...

**Comment by sidex15** [comment]
or did you mean if you remove the susfs to the kernel, it works fine?

**Comment by Autotto** [comment]
probably same issues. my kali nethunter chroot cant mount after i flashing susfs patched kernel.
if i flash back to vanilla kernel , it work.

p.s: reproducible💧

**Comment by sidex15** [comment]
> probably same issues. my kali nethunter chroot cant mount after i flashing susfs patched kernel. if i flash back to vanilla kernel , it work.
> 
> p.s: reproducible💧

sorry for the late reply. This is due to mountinfo being hidden by the SUSFS.
To fix this, if you're the kernel maintainer, you should add this code in `proc_namespace.c`
``` diff
#include "pnode.h"
#include "internal.h"

+#ifdef CONFIG_KSU_SUSFS_SUS_MOUNT
+extern bool susfs_is_current_ksu_domain(void);
+#endif
```
Then, in the same file, you should find:
```c
if (unlikely(r->mnt_id >= DEFAULT_SUS_MNT_ID))
```
then replace them all with
```c
if (unlikely((r->mnt_id >= DEFAULT_SUS_MNT_ID) && !susfs_is_current_ksu_domain()))
```

And your kali nethunter should work.

I think this would be the same fix for the first issue

**Comment by fxynb399** [comment]
> 或者您的意思是，如果您将 SUSFS 删除到内核中，它就可以正常工作了？

谢谢您的回复，我才发现我是刷入了这个项目 [GKI_KernelSU_SUSFS](https://github.com/WildPlusKernel/GKI_KernelSU_SUSFS) 才导致无法挂载，如果我仅刷入gki，然后再刷入你这个模块就正常挂载

**Comment by StanleyLegEnd1024** [comment]
我也无法挂载我的存储，转回lkm就没事了

**Comment by fxynb399** [comment]
> 我也无法挂载我的存储，转回lkm就没事了

单独刷gki，再单独刷susfs 是正常的，我现在就这么用

**Comment by StanleyLegEnd1024** [comment]
可能是版本问题吧


fanxiangyu399 ***@***.***> 于 2025年5月3日周六 20:42写道：

**Comment by Autotto** [comment]
> > probably same issues. my kali nethunter chroot cant mount after i flashing susfs patched kernel. if i flash back to vanilla kernel , it work.
> > p.s: reproducible💧
> 
> sorry for the late reply. This is due to mountinfo being hidden by the SUSFS. To fix this, if you're the kernel maintainer, you should add this code in `proc_namespace.c`
> 
> #include "pnode.h"
> #include "internal.h"
> 
> +#ifdef CONFIG_KSU_SUSFS_SUS_MOUNT
> +extern bool susfs_is_current_ksu_domain(void);
> +#endif
> Then, in the same file, you should find:
> 
> if (unlikely(r->mnt_id >= DEFAULT_SUS_MNT_ID))
> then replace them all with
> 
> if (unlikely((r->mnt_id >= DEFAULT_SUS_MNT_ID) && !susfs_is_current_ksu_domain()))
> And your kali nethunter should work.
> 
> I think this would be the same fix for the first issue

look like [susfs4ksu](https://gitlab.com/simonpunk/susfs4ksu) has [fixed this issues](https://gitlab.com/simonpunk/susfs4ksu/-/commit/c75391d3eebea078dad487c91ee8eaa8e1cc4398) 🤔

**Comment by sidex15** [comment]
> look like [susfs4ksu](https://gitlab.com/simonpunk/susfs4ksu) has [fixed this issues](https://gitlab.com/simonpunk/susfs4ksu/-/commit/c75391d3eebea078dad487c91ee8eaa8e1cc4398) 🤔

Yes it's fixed and you can switch it on userspace via the command:

https://github.com/user-attachments/assets/0a8c7b31-0f6f-49f5-9d90-cfa3a4c5fddd

**Comment by Autotto** [comment]
> > look like [susfs4ksu](https://gitlab.com/simonpunk/susfs4ksu) has [fixed this issues](https://gitlab.com/simonpunk/susfs4ksu/-/commit/c75391d3eebea078dad487c91ee8eaa8e1cc4398) 🤔
> 
> Yes it's fixed and you can switch it on userspace via the command:
> 
>  test-1.mp4

i think susfs aslo make this issue ↓ (i tested), but at last i can have a Nethunter "Lite" :-/

[![cant-load-driver.png](https://i.postimg.cc/LsXLcDwC/cant-load-driver.png)](https://postimg.cc/JsfsJN1Z)

**Comment by sidex15** [comment]
Issue solved by the owner, and susfs v1.5.7 newer commits solved the issue. issue closed

**Comment by NCLnclNCL** [comment]
> > probably same issues. my kali nethunter chroot cant mount after i flashing susfs patched kernel. if i flash back to vanilla kernel , it work.
> > p.s: reproducible💧
> 
> sorry for the late reply. This is due to mountinfo being hidden by the SUSFS. To fix this, if you're the kernel maintainer, you should add this code in `proc_namespace.c`
> 
> #include "pnode.h"
> #include "internal.h"
> 
> +#ifdef CONFIG_KSU_SUSFS_SUS_MOUNT
> +extern bool susfs_is_current_ksu_domain(void);
> +#endif
> Then, in the same file, you should find:
> 
> if (unlikely(r->mnt_id >= DEFAULT_SUS_MNT_ID))
> then replace them all with
> 
> if (unlikely((r->mnt_id >= DEFAULT_SUS_MNT_ID) && !susfs_is_current_ksu_domain()))
> And your kali nethunter should work.
> 
> I think this would be the same fix for the first issue

because i am using patch 1.5.5 so it has not fixed this error and mnt, is it the reason for the error?
